description: Apps and Engines when toolkit is run from outside a project.
engines:
  tk-desktop:
    apps: null
    collapse_rules: []
    debug_logging: false
    default_group: Studio
    groups: []
    hook_launch_python: default
    location: {name: tk-desktop, type: app_store, version: v2.0.5}
    show_recents: true
frameworks:
  tk-framework-adminui_v0.x.x:
    location: {name: tk-framework-adminui, type: app_store, version: v0.1.2}
  tk-framework-login_v1.x.x:
    location: {name: tk-framework-login, type: app_store, version: v1.2.1}
  tk-framework-qtwidgets_v1.x.x:
    location: {name: tk-framework-qtwidgets, type: app_store, version: v1.0.1}
  tk-framework-shotgunutils_v2.x.x:
    location: {name: tk-framework-shotgunutils, type: app_store, version: v2.4.1}
